name: agent-explore
channels:
  - conda-forge
dependencies:
  - python=3.12
  - aiohttp
  - anyio
  - attrs
  - beautifulsoup4
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - dataclasses-json
  - decorator
  - defusedxml
  - ipykernel
  - jsonschema
  - jupyterlab
  - langchain
  - langchain-core
  - langchain-experimental
  - langchain-openai
  - langsmith
  - numpy
  - openai
  - pandas
  - pip
  - playwright
  - pydantic
  - python-dateutil
  - pyyaml
  - requests
  - setuptools
  - six
  - sqlalchemy
  - tenacity
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_inspect
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml